# Generated by Django 2.2.2 on 2020-02-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.Booking'),
            preserve_default=False,
        ),
    ]
