# Generated by Django 2.2.2 on 2020-02-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_profile_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookings',
        ),
    ]
